### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by dilawar** [bliscprojects/ArchivesSpace#8]
- [ ] Modifying the public user interface to include NCBS logo and changing front page text to have NCBS specific content.

Something like what CSHL has done. https://archivesspace.cshl.edu/
Ours looks like this right now (out of the box version): http://catalogue.archives.ncbs.res.in/

- [ ] Running and activating two ArchivesSpace plug-ins for categorizing by standard names and subjects. They are called LCNAF (Library of Congress Name Authority File) and LCSH (Library of Congress Subject Headings). They should install and work out of the box, but we have difficulty with this and get really odd error messages that seem to indicate that there is some kind of a firewall. I can forward you these error messages later when you get to it.
- [ ] In a few weeks, we will need to upgrade to a new ArchivesSpace version. There is documentation on their platform on how to do upgrades. This upgrade package includes a plugin to import from CSV template directly onto ArchivesSpace, which will make the workflow so much faster. If this release doesn't happen in time, then we can also download and install the plugin from the ArchivesSpace github for this.
